#Basic config yaml file for the search

#SLURM

n_nodes: 1
n_cpu: 16
computing_time: 2:00:00



#Sub-banded search
subband_search: False
channels: [[0,128],[128,256]]
band_threshold: 100
overlap: True

#RFI Exicision
mask_name: "mask"
time_start: 0
nsamps_gulpr: 8192
sk_sigma: 5
sg_sigma: 5
sg_window: 43
plot: True

#Heimdall
dm: [0,1000]
dm_tolerance: 1.25
boxcar_max: 10
baseline_length: None
gpu_id: None
rfi_no_narrow: None
rfi_no_broad: None
no_scrunching: None
scrunching_tol: None
rfi_tol: None
nsamps_gulp: None
fswap: None

#Filtering with prepare_for_fetch.py
snr: 6
dmf: [0,1000]
n_members: 10

#FETCH
probability: 0.75
model: [a,h]
